# Generated by Django 6.0.4 on 2026-05-03 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.DecimalField(decimal_places=4, max_digits=6)),
                ('predicted_enroll', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='enrollmenthistory',
            name='semester_year',
        ),
        migrations.AddField(
            model_name='course',
            name='lab_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='lecture_hours',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='enrollmenthistory',
            name='credit_hours',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='enrollmenthistory',
            name='semester_label',
            field=models.CharField(default='Fall', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollmenthistory',
            name='term',
            field=models.CharField(default='2024_Fall', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollmenthistory',
            name='year',
            field=models.IntegerField(default='2024'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flaggedstudent',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.predictionrun'),
        ),
        migrations.AddField(
            model_name='predictionrun',
            name='semester_predicted',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='predictionrun',
            name='total_courses_predicted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predictionrun',
            name='total_students_processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='student',
            name='degree_type',
            field=models.CharField(choices=[('Bachelor', 'Bachelor'), ('Technical', 'Technical')], default='Bachelor', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='needs_rem_arabic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='needs_rem_english',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='needs_rem_math',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courseprediction',
            name='confidence_score',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='enrollmenthistory',
            name='status',
            field=models.CharField(default='Completed', max_length=50),
        ),
        migrations.AlterField(
            model_name='flaggedstudent',
            name='prediction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.courseprediction'),
        ),
        migrations.AlterField(
            model_name='predictionrun',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='courseprediction',
            unique_together={('run', 'course')},
        ),
        migrations.AddIndex(
            model_name='enrollmenthistory',
            index=models.Index(fields=['student', 'year', 'term'], name='core_enroll_student_f8b44a_idx'),
        ),
        migrations.AddField(
            model_name='studentprediction',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AddField(
            model_name='studentprediction',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.predictionrun'),
        ),
        migrations.AddField(
            model_name='studentprediction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AddIndex(
            model_name='studentprediction',
            index=models.Index(fields=['run', 'student'], name='core_studen_run_id_78219d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentprediction',
            unique_together={('run', 'student', 'course')},
        ),
    ]
